server:
  port: 8080

spring:
  application:
    name: "Spring-homework-7-role"

  # H2 database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/auth
    username: sa
    password:
  # консоль для отладки
  h2:
    console:
      enabled: true
      path: /h2-console

  # Spring Jpa Hibernate
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

    generate-ddl: true
    defer-datasource-initialization: true
    open-in-view: false


  thymeleaf:
    cache: false
